#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'hello coway this is pre push test'

FORBIDDEN_HTTPS_URL="https://github.com/cw-mbc0481/sketch.git" # remote url (https)
FORBIDDEN_SSH_URL="git@github.com:cw-mbc0481/sketch.git" # remote url (ssh)
FORBIDDEN_REF="refs/heads/main" # branch ref

ARR_GIT_PARAMS=($(echo $HUSKY_GIT_PARAMS))
ARR_GIT_STDIN=($(echo $HUSKY_GIT_STDIN))

remote=${ARR_GIT_PARAMS[0]}
url=${ARR_GIT_PARAMS[1]}

local_ref=${ARR_GIT_STDIN[0]}
local_sha=${ARR_GIT_STDIN[1]}
remote_ref=${ARR_GIT_STDIN[2]}
remote_sha=${ARR_GIT_STDIN[3]}

if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    exit 0 # Forked Project 에서는 제한하지 않음
fi

if read local_ref local_sha remote_ref remote_sha
then
    if [ "$remote_ref" == "$FORBIDDEN_REF" ]
    then
        echo "DO NOT PUSH it master"
        exit 1 # 금지된 ref 로 push 를 실행하면 에러
    fi
fi

echo '현재 시간'
today=$(date)
echo $today

echo 'prettier 실행'
npm run format

echo 'lint 실행'
npm run lint:fix

echo 'build 실행'
npm run build

echo 'test 실행'
npm run test:run


exit 0