on:
  workflow_dispatch:

name: PRD Deploy to S3

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss

      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3

      - name: Show version number
        run: echo "${{ steps.package-version.outputs.current-version}}"

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          release_name: Release v${{ steps.package-version.outputs.current-version}}
          body_path: ./releaseNote.md
          draft: false
          prerelease: false

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          DEBUG: false
          VITE_APP_VERSION: ${{ secrets.APP_VERSION }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          file_name: .env.prd

      - name: Install Dependency
        run: npm install

      - name: Build
        run: npm run build:env 'prd'
