on:
  workflow_dispatch:

name: PRD Deploy to S3

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          DEBUG: false
          VITE_APP_VERSION: ${{ secrets.APP_VERSION }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          file_name: .env.prd

      - name: Install Dependency
        run: npm install

      - name: Build
        run: npm run build:env 'prd'

on:
  pull_request:
    branches: [main]
    types: [closed]
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false