on:
  pull_request:
    branches: [development]
    types: [closed]

name: DEV Deploy to S3

env:
  VITE_APP_VERSION: ${{secrets.APP_VERSION}}
  VITE_APP_SECRET_KEY: ${{secrets.SECRET_KEY}}

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          DEBUG: false
          VITE_APP_VERSION: ${{ secrets.APP_VERSION }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          file_name: .env.dev

      - name: cat envfile
        run: cat ./.env.dev

      - name: Install Dependency
        run: npm install

      - name: Build
        run: npm run build:env 'dev'
