on:
  push:
    branch: [main]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        env:
          PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: Release ${{ env.PACKAGE_VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
